---
- name: 1. Install MariaDB server package
  yum: 
    name: mariadb-server 
    state: latest

- name: 2. Start Mysql Service
  service: 
    name: mysql
    enabled: true
    state: started

- name: 3.Install python Mysql package #required for mysql_db tasks
  yum: 
    name: MySQL-python
    state: latest

- name: 3a. Download epel-repo, instal repo
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: 3.c Install python2-PyMySQL
  yum: 
    name: python2-PyMySQL
    state: latest

- name: 4. Create a new database
  mysql_db: 
    name: demo 
    state: present

- name: 5. Create a database user
  mysql_user: 
    name: demo 
    password: demo 
    priv: '*.*:ALL' 
    host: localhost 
    state: present

- name: 6a. Copy sample data
  copy: 
    src: dump.sql 
    dest: /tmp/dump.sql

- name: 6b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: 7. Restart Apache
  service: 
    name: httpd 
    state: restarted

- name: 8. install Hello World PHP script with database
  copy: 
    src: db.php 
    dest: /var/www/html/db.php 
    mode: 0664
